// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frjuvbgiqiucgrayeuqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyanV2YmdpcWl1Y2dyYXlldXFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMzk3NjAsImV4cCI6MjA4NjkxNTc2MH0.eotClxCK1t5g-7w-2D19DWmTiRocfxcnkiihMPsf8EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});